<?php

namespace bs\IDP\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * IDPDeliverAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPDeliverAddressRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('longname' => 'ASC'));
    }
	public function getAll( )
	{
		$querySelect = "SELECT b FROM bsIDPBackofficeBundle:IDPDeliverAddress b";
		$query = $this->getEntityManager()->createQuery($querySelect);
		return $query->getArrayResult();
	}

    public function getAllIndexedOnID( ){
        $result = [];
        $deliverAddresses = $this->getAll();
        if( !$deliverAddresses ) return null;

        foreach( $deliverAddresses as $deliverAddress ){
            $result[$deliverAddress['id']] = $deliverAddress;
        }
        return $result;
    }

    public function countDeliverAddress( $search ){

		$queryStr = 'SELECT COUNT(d.id) ';
		$queryStr .= ' FROM bsIDPBackofficeBundle:IDPDeliverAddress d ';
        if( $search )
            $queryStr .= " WHERE d.longname LIKE '%$search%' ";

		$query = $this->getEntityManager()->createQuery( $queryStr );

		return $query->getSingleScalarResult();
	}

	public function loadDeliverAddressDatas( $search, $sort, $order, $limit, $offset ){
		$queryStr = 'SELECT d ';
		$queryStr .= ' FROM bsIDPBackofficeBundle:IDPDeliverAddress d ';
        if( $search )
            $queryStr .= " WHERE d.longname LIKE '%$search%' ";
		$queryStr .= " ORDER BY d.$sort $order ";

		$query = $this->getEntityManager()
			->createQuery( $queryStr );
		if( $limit > 0 )
			$query->setMaxResults( $limit );

		$query->setFirstResult( $offset )
			->setHint(Query::HINT_INCLUDE_META_COLUMNS, true);

		return $query->getResult();
	}

}
