<?php

namespace bs\IDP\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * IDPLocalizationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPLocalizationsRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('longname' => 'ASC'));
    }

    public function getAll( )
    {
        $querySelect = "SELECT l FROM bsIDPBackofficeBundle:IDPLocalizations l";
        $query = $this->getEntityManager()->createQuery($querySelect);
        return $query->getArrayResult();
    }

    public function getAllIndexedOnID( ){
        $result = [];
        $localizations = $this->getAll();
        if( !$localizations ) return null;

        foreach( $localizations as $localization ){
            $result[$localization['id']] = $localization;
        }
        return $result;
    }

    public function countLocalizations( $search ){

        $queryStr = 'SELECT COUNT(l.id) ';
        $queryStr .= ' FROM bsIDPBackofficeBundle:IDPLocalizations l ';
        if( $search )
            $queryStr .= " WHERE l.longname LIKE '%$search%' ";

        $query = $this->getEntityManager()->createQuery( $queryStr );

        return $query->getSingleScalarResult();
    }

    public function loadLocalizationsDatas( $search, $sort, $order, $limit, $offset ){
        $queryStr = 'SELECT l ';
        $queryStr .= ' FROM bsIDPBackofficeBundle:IDPLocalizations l ';
        if( $search )
            $queryStr .= " WHERE l.longname LIKE '%$search%' ";
        $queryStr .= " ORDER BY l.$sort $order ";

        $query = $this->getEntityManager()
            ->createQuery( $queryStr )
            ->setMaxResults( $limit )
            ->setFirstResult( $offset )
            ->setHint(Query::HINT_INCLUDE_META_COLUMNS, true);

        return $query->getResult();
    }

    public function findOneWithConstraint( $longname, $localization_id ){

        $query = $this->createQueryBuilder( 'l' )
            ->select( 'l' )
            ->where( 'l.longname = :longname' )
            ->andWhere( 'l.id = :lid' )
            ->setParameter( 'longname', $longname )
            ->setParameter( 'lid', $localization_id );

        return $query->getQuery()->getResult();
    }

    public function findPrevNext( $localizationId, $sortASC ){
        $em = $this->getEntityManager();

        // On récupère le nom de l'élément courant
        $query = $em->createQuery( "SELECT t.longname FROM bsIDPBackofficeBundle:IDPLocalizations t WHERE t.id = :currentid" )
            ->setParameter( 'currentid', $localizationId );
        $currentNameRsp = $query->getResult();
        if( !$currentNameRsp ) return null;
        $currentName = $currentNameRsp[0]['longname'];

        // Get next when ordered ASC
        $query = $em->createQuery( "SELECT MIN(t.longname) as longname FROM bsIDPBackofficeBundle:IDPLocalizations t WHERE t.longname > :currentname ORDER by t.longname" )
            ->setParameter( 'currentname' , $currentName )
            ->setMaxResults( 1 );
        $nextEntryRsp = $query->getResult();
        if( !$nextEntryRsp ) $nextEntryName = null;
        else $nextEntryName = $nextEntryRsp[0]['longname'];

        $query = $em->createQuery( "SELECT t.id FROM bsIDPBackofficeBundle:IDPLocalizations t WHERE t.longname = :nextname" )
            ->setParameter( 'nextname' , $nextEntryName );
        $nextEntryRsp = $query->getResult();
        if( !$nextEntryRsp ) $nextEntryId = null;
        else $nextEntryId = $nextEntryRsp[0]['id'];

        // Get previous when ordered ASC
        $query = $em->createQuery( "SELECT MAX(t.longname) as longname FROM bsIDPBackofficeBundle:IDPLocalizations t WHERE t.longname < :currentname ORDER by t.longname" )
            ->setParameter( 'currentname' , $currentName )
            ->setMaxResults( 1 );
        $previousEntryRsp = $query->getResult();
        if( !$previousEntryRsp ) $previousEntryName = null;
        else $previousEntryName = $previousEntryRsp[0]['longname'];

        $query = $em->createQuery( "SELECT t.id FROM bsIDPBackofficeBundle:IDPLocalizations t WHERE t.longname = :previousname" )
            ->setParameter( 'previousname' , $previousEntryName );
        $previousEntryRsp = $query->getResult();
        if( !$previousEntryRsp ) $previousEntryId = null;
        else $previousEntryId = $previousEntryRsp[0]['id'];

        if( $sortASC == 1 )
            return [
                'previous' => [ 'id' => ($previousEntryId===null)?null:$previousEntryId, 'longname'=> ($previousEntryName===null)?null:$previousEntryName ],
                'current' => ['id' => $localizationId, 'longname' => $currentName ],
                'next' => [ 'id' => ($nextEntryId===null)?null:$nextEntryId, 'longname'=> ($nextEntryName===null)?null:$nextEntryName ]
            ];
        else // Order seems to be DESC, so invert
            return [
                'previous' => [ 'id' => ($nextEntryId===null)?null:$nextEntryId, 'longname'=> ($nextEntryName===null)?null:$nextEntryName ],
                'current' => ['id' => $localizationId, 'longname' => $currentName ],
                'next' => [ 'id' => ($previousEntryId===null)?null:$previousEntryId, 'longname'=> ($previousEntryName===null)?null:$previousEntryName ]
            ];

    }
}
