<?php

namespace bs\IDP\BackofficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * IDPProviderConnectorBackupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPProviderConnectorBackupRepository extends EntityRepository
{
    public function getArray( $userId ){
        $querySelect = "SELECT pcb FROM bsIDPBackofficeBundle:IDPProviderConnectorBackup pcb WHERE pcb.userid = '$userId'";
        $query = $this->getEntityManager()->createQuery($querySelect);
        $query = $this->getEntityManager()
            ->createQuery( $querySelect )
            ->setMaxResults( 1 );
        return $query->getArrayResult();
    }
}
