<?php

namespace Proxies\__CG__\bs\IDP\BackofficeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IDPServices extends \bs\IDP\BackofficeBundle\Entity\IDPServices implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'id', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'longname', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'legalEntities', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'documentNatures', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'descriptions1', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'descriptions2', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'budgetCodes', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'providers'];
        }

        return ['__isInitialized__', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'id', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'longname', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'legalEntities', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'documentNatures', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'descriptions1', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'descriptions2', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'budgetCodes', '' . "\0" . 'bs\\IDP\\BackofficeBundle\\Entity\\IDPServices' . "\0" . 'providers'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (IDPServices $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongname($longname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongname', [$longname]);

        return parent::setLongname($longname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongname', []);

        return parent::getLongname();
    }

    /**
     * {@inheritDoc}
     */
    public function addLegalEntity(\bs\IDP\BackofficeBundle\Entity\IDPLegalEntities $legalEntities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLegalEntity', [$legalEntities]);

        return parent::addLegalEntity($legalEntities);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLegalEntity(\bs\IDP\BackofficeBundle\Entity\IDPLegalEntities $legalEntities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLegalEntity', [$legalEntities]);

        return parent::removeLegalEntity($legalEntities);
    }

    /**
     * {@inheritDoc}
     */
    public function getLegalEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLegalEntities', []);

        return parent::getLegalEntities();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumentNatures(\bs\IDP\BackofficeBundle\Entity\IDPDocumentNatures $documentNatures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumentNatures', [$documentNatures]);

        return parent::addDocumentNatures($documentNatures);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocumentNatures(\bs\IDP\BackofficeBundle\Entity\IDPDocumentNatures $documentNatures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocumentNatures', [$documentNatures]);

        return parent::removeDocumentNatures($documentNatures);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentNatures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentNatures', []);

        return parent::getDocumentNatures();
    }

    /**
     * {@inheritDoc}
     */
    public function addDescriptions1(\bs\IDP\BackofficeBundle\Entity\IDPDescriptions1 $descriptions1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDescriptions1', [$descriptions1]);

        return parent::addDescriptions1($descriptions1);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDescriptions1(\bs\IDP\BackofficeBundle\Entity\IDPDescriptions1 $descriptions1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDescriptions1', [$descriptions1]);

        return parent::removeDescriptions1($descriptions1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptions1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptions1', []);

        return parent::getDescriptions1();
    }

    /**
     * {@inheritDoc}
     */
    public function addDescriptions2(\bs\IDP\BackofficeBundle\Entity\IDPDescriptions2 $descriptions2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDescriptions2', [$descriptions2]);

        return parent::addDescriptions2($descriptions2);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDescriptions2(\bs\IDP\BackofficeBundle\Entity\IDPDescriptions2 $descriptions2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDescriptions2', [$descriptions2]);

        return parent::removeDescriptions2($descriptions2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptions2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptions2', []);

        return parent::getDescriptions2();
    }

    /**
     * {@inheritDoc}
     */
    public function addBudgetCode(\bs\IDP\BackofficeBundle\Entity\IDPBudgetCodes $budgetCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBudgetCode', [$budgetCodes]);

        return parent::addBudgetCode($budgetCodes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBudgetCode(\bs\IDP\BackofficeBundle\Entity\IDPBudgetCodes $budgetCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBudgetCode', [$budgetCodes]);

        return parent::removeBudgetCode($budgetCodes);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetCodes', []);

        return parent::getBudgetCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function addProvider(\bs\IDP\BackofficeBundle\Entity\IDPProviders $providers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProvider', [$providers]);

        return parent::addProvider($providers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProvider(\bs\IDP\BackofficeBundle\Entity\IDPProviders $providers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProvider', [$providers]);

        return parent::removeProvider($providers);
    }

    /**
     * {@inheritDoc}
     */
    public function getProviders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProviders', []);

        return parent::getProviders();
    }

}
