<?php

namespace bs\Core\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * bsRightsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bsRightsRepository extends EntityRepository
{
	public function findAllScaleMin( $scaleMin = 0 ){
		$requestStr = "SELECT r ";
		$requestStr .= " FROM bsCoreUsersBundle:bsRights r ";
		$requestStr .= " WHERE r.scale >= $scaleMin ";

		$query = $this->getEntityManager()->createQuery( $requestStr );

		return $query->getResult();
	}

}
