<?php

namespace bs\Core\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * bsRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bsRolesRepository extends EntityRepository
{
	public function findAllScaleMin( $scaleMin = 0 ){
		$requestStr = "SELECT r ";
		$requestStr .= " FROM bsCoreUsersBundle:bsRoles r ";
		if( $scaleMin > 0 )
			$requestStr .= " WHERE r.scale > $scaleMin ";

		$query = $this->getEntityManager()->createQuery( $requestStr );

		return $query->getResult();
	}

	public function count()
	{
		return $this->createQueryBuilder('id')
		    ->select('COUNT(id)')
		    ->getQuery()
		    ->getSingleScalarResult()
		;
	}

}
