<?php

namespace bs\Core\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IDPUserExtensionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPUserExtensionsRepository extends EntityRepository
{
	public function delete( $userID ){
		$queryStr = 'DELETE ';
		$queryStr .= ' FROM bsCoreUsersBundle:IDPUserExtensions ue ';
		$queryStr .= " WHERE ue.user=$userID ";

		$query = $this->getEntityManager()->createQuery( $queryStr );

		return $query->getResult();
	}
}
