<?php

namespace bs\Core\UsersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IDPUserServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPUserServicesRepository extends EntityRepository
{
	public function delete( $userID ){
		$queryStr = 'DELETE ';
		$queryStr .= ' FROM bsCoreUsersBundle:IDPUserServices us ';
		$queryStr .= " WHERE us.user=$userID ";

		$query = $this->getEntityManager()->createQuery( $queryStr );

		return $query->getResult();
	}

}
