<?php

namespace bs\IDP\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * bsMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bsMessagesRepository extends EntityRepository
{
}
