<?php

namespace bs\IDP\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IDPArchivesStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPArchivesStatusRepository extends EntityRepository
{
	public function getAll( )
	{
		$querySelect = "SELECT s FROM bsIDPArchiveBundle:IDPArchivesStatus s";
		$query = $this->getEntityManager()->createQuery($querySelect);
		return $query->getArrayResult();
	}

    public function getAllIndexedOnID( ){
        $result = [];
        $statuses = $this->getAll();
        if( !$statuses ) return null;

        foreach( $statuses as $status ){
            $result[$status['id']] = $status;
        }
        return $result;
    }

}
