<?php

namespace bs\IDP\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query;


/**
 * IDPImportRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPImportRepository extends EntityRepository
{
    public function getAllSortedByBegin( $inversed = false ){
        $querySelect = 'SELECT i ';
        $querySelect .= ' FROM bsIDPArchiveBundle:IDPImport i ';
        $querySelect .= ' ORDER BY i.date_begin ';
        $querySelect .= ($inversed?'DESC':'ASC');

        $query = $this->getEntityManager()->createQuery( $querySelect );

        return $query->getResult();
    }
}



