<?php

namespace bs\IDP\ArchiveBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query;


/**
 * IDPImportCommRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IDPImportCommRepository extends EntityRepository
{
    public function removeAllWithImportId( $importID ){
        $queryStr = 'DELETE  ';
        $queryStr .= ' FROM bsIDPArchiveBundle:IDPImportComm i ';
        $queryStr .= ' WHERE i.import_id = '.$importID;

        $query = $this->getEntityManager()
            ->createQuery( $queryStr );

        return $query->getResult();

    }
}



