<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgckwto\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgckwto/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRgckwto.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRgckwto\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRgckwto\appDevDebugProjectContainer([
    'container.build_hash' => 'Rgckwto',
    'container.build_id' => '14ff6737',
    'container.build_time' => 1759330716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRgckwto');
