
bs_idp_archivist_json_legalentities_list:
    path:     /list/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitieslist }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_delete:
    path:     /delete/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitiesdelete }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_add:
    path:     /add/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitiesadd }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_modify:
    path:     /modify/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitiesmodify }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_links_list:
    path:     /links/list/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitieslinkslist }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_links_set:
    path:     /links/set/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitieslinksset }
    requirements:
        _method: GET

bs_idp_archivist_json_legalentities_links_unset:
    path:     /links/unset/
    defaults: { _controller: bsIDPArchiveBundle:ManageDBLegalEntitiesJson:legalentitieslinksunset }
    requirements:
        _method: GET
